import {
  ArrowLeftRight,
  ArrowUpDown,
  Award,
  Binary,
  Bot,
  Boxes,
  Braces,
  Brain,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  Coins,
  Combine,
  Compass,
  Crown,
  Database,
  DatabaseZap,
  Diamond,
  Eye,
  Flag,
  Flame,
  Footprints,
  Gem,
  GitMerge,
  GraduationCap,
  Grid3x3,
  Hash,
  Layers,
  Layers3,
  Link2,
  Medal,
  Milestone,
  Mountain,
  Network,
  PanelLeftClose,
  PlayCircle,
  Rabbit,
  RefreshCw,
  Rocket,
  ScrollText,
  SearchCode,
  Shapes,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  SpellCheck,
  Star,
  Swords,
  Target,
  TreeDeciduous,
  TreePine,
  Trophy,
  Undo2,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// Every icon the string-keyed datasets (src/data/patterns.ts, engine/achievements.ts) refer to
// by name — imported EXPLICITLY so the bundler tree-shakes lucide-react down to these ~55
// glyphs. The previous `import * as LucideIcons` in five files pulled the entire icon library
// (>1000 icons) into the main chunk. Adding an icon name to a dataset means adding it here;
// src/utils/engine/__tests__/achievements.test.ts and src/data's tests pin that every
// referenced name resolves.
export const ICON_MAP: Record<string, LucideIcon> = {
  ArrowLeftRight,
  ArrowUpDown,
  Award,
  Binary,
  Bot,
  Boxes,
  Braces,
  Brain,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  Coins,
  Combine,
  Compass,
  Crown,
  Database,
  DatabaseZap,
  Diamond,
  Eye,
  Flag,
  Flame,
  Footprints,
  Gem,
  GitMerge,
  GraduationCap,
  Grid3x3,
  Hash,
  Layers,
  Layers3,
  Link2,
  Medal,
  Milestone,
  Mountain,
  Network,
  PanelLeftClose,
  PlayCircle,
  Rabbit,
  RefreshCw,
  Rocket,
  ScrollText,
  SearchCode,
  Shapes,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  SpellCheck,
  Star,
  Swords,
  Target,
  TreeDeciduous,
  TreePine,
  Trophy,
  Undo2,
  Zap,
};

export function iconByName(name: string, fallback: LucideIcon): LucideIcon {
  return ICON_MAP[name] ?? fallback;
}
