import familiesJson from '@/data/families.json';
import subpatternsJson from '@/data/subpatterns.json';
import type { ProblemFamily, SubpatternGroup } from '@/types';

// Curriculum intelligence, generated by scripts/generate-questions.mjs from the
// hand-verified scripts/data/curriculum.json — never hand-edit the JSON outputs.
export const FAMILIES = familiesJson as ProblemFamily[];
export const SUBPATTERNS = subpatternsJson as Record<string, SubpatternGroup[]>;

export const familyById: Record<string, ProblemFamily> = Object.fromEntries(
  FAMILIES.map((f) => [f.id, f]),
);

// Role display order for family member lists: the learning on-ramp, not authoring order.
export const FAMILY_ROLE_ORDER = ['canonical', 'warmup', 'standard', 'variant', 'stretch'] as const;

export const FAMILY_ROLE_LABEL: Record<string, string> = {
  canonical: 'Canonical',
  warmup: 'Warm-up',
  standard: 'Standard',
  variant: 'Variant',
  stretch: 'Stretch',
};
