import projectsJson from '@/data/mlProjects.json';

/**
 * The ML project ladder — generated by scripts/generate-questions.mjs from
 * scripts/data/ml-projects.json. Never hand-edit the JSON.
 *
 * The `baseline` field is why this file exists. A project with a stated dumb model and its
 * actual score is engineering; the same project without one is a tutorial, because there is no
 * way to tell whether anything you built helped. So the baseline is surfaced before the
 * objective, the experiments, or anything else — and where `score` is null the UI says the
 * learner has to establish it rather than quietly hiding the field, since a null there is a
 * refusal to invent a number, not a gap in the research.
 *
 * `metric.why` always renders next to `metric.name`, because arguing the metric against its
 * obvious alternative (RMSE not MAE, PR-AUC not ROC-AUC, p95 not mean) is the teaching.
 */
export type MlProjectTier =
  | 'beginner'
  | 'intermediate'
  | 'advanced'
  | 'deep-learning'
  | 'nlp'
  | 'modern-ai'
  | 'production';

export interface MlProjectDataset {
  name: string;
  /** Where it comes from, fetched and confirmed reachable without a login on `checkedAt`. */
  source: string;
  /** Counts read off the downloaded artifact, not off a description page. */
  size: string;
  license: string;
  checkedAt: string;
  note?: string;
}

export interface MlProjectBaseline {
  /** The dumb model, named. */
  model: string;
  /** Its measured score, or null where the figure is a property of the learner's own system. */
  score: string | null;
  /** What the score is measured in. */
  metric: string;
  /** Where the number came from — or, when `score` is null, who has to establish it. */
  note?: string;
}

export interface MlProjectMetric {
  name: string;
  /** The argument against the obvious alternative. Always rendered with the name. */
  why: string;
}

export interface MlProject {
  id: string;
  tier: MlProjectTier;
  /** Position within the tier. The ladder is cumulative — later projects ship earlier ones. */
  order: number;
  title: string;
  objective: string;
  dataset: MlProjectDataset;
  baseline: MlProjectBaseline;
  metric: MlProjectMetric;
  experiments: string[];
  errorAnalysis: string[];
  iteration: string;
  /** Null in the early tiers, where shipping would be theatre. */
  deployment: string | null;
  /** Deliberately unanswered — the answers are properties of your own runs. */
  retrospective: string[];
  hours: number;
  /** Implementation-track ids to have done first. Verified against mlTracks.json. */
  prereqTracks: string[];
  /** A real week id from aimlCourse.ts, or null where the course genuinely has no such week. */
  weekId: string | null;
}

export const ML_PROJECTS = projectsJson as MlProject[];

export const mlProjectById: Record<string, MlProject> = Object.fromEntries(
  ML_PROJECTS.map((p) => [p.id, p]),
);

/** Tier reading order — the ladder's own sequence, not alphabetical. */
export const ML_TIER_ORDER: MlProjectTier[] = [
  'beginner',
  'intermediate',
  'advanced',
  'deep-learning',
  'nlp',
  'modern-ai',
  'production',
];

export const ML_TIER_LABEL: Record<MlProjectTier, string> = {
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  advanced: 'Advanced',
  'deep-learning': 'Deep learning',
  nlp: 'NLP',
  'modern-ai': 'Modern AI',
  production: 'Production',
};

/** The ladder in reading order: tier sequence first, then `order` inside the tier. */
export const ML_PROJECTS_IN_ORDER: MlProject[] = [...ML_PROJECTS].sort(
  (a, b) => ML_TIER_ORDER.indexOf(a.tier) - ML_TIER_ORDER.indexOf(b.tier) || a.order - b.order,
);

export const totalProjectHours = (projects: MlProject[] = ML_PROJECTS): number =>
  projects.reduce((sum, p) => sum + p.hours, 0);
