import tracksJson from '@/data/mlTracks.json';

/**
 * From-scratch ML implementation tracks — generated by scripts/generate-questions.mjs from
 * scripts/data/ml-implementation.json (itself merged from the two authored halves). Never
 * hand-edit the JSON: fix the source and re-run the generator.
 *
 * Each track is a five-stage ladder, and the order is the teaching:
 *
 *   math → scratch → library → experiment → failure
 *
 * You derive it, you write it in numpy, you meet the library that already does it, you run the
 * two against each other on real data, and then you learn the ways it breaks. `failure` is the
 * highest-value stage in the dataset — several entries were reproduced deliberately to get the
 * observed symptom right — which is why the UI never hides it behind a second disclosure.
 *
 * `weekId` is null wherever the 26-week AI/ML course genuinely has no matching week (it runs
 * neural nets → transformers → PyTorch → agents → RAG → fine-tuning → RL → evals, so classical
 * ML has nowhere honest to attach). The generator requires the null to be explicit.
 */
export type MlStageId = 'math' | 'scratch' | 'library' | 'experiment' | 'failure';

export interface MlSymbol {
  symbol: string;
  meaning: string;
}

export interface MlMathStage {
  summary: string;
  /** The derivation itself, pre-formatted — rendered in a monospace block, not as prose. */
  detail: string;
  symbols: MlSymbol[];
}

export interface MlScratchStage {
  summary: string;
  /** The functions to write, in the order they should be written. */
  checklist: string[];
  /** Array shapes at every step — the single most common source of a silent bug. */
  shapes: string[];
}

export interface MlLibraryStage {
  summary: string;
  /** The exact library symbols this stage uses. */
  api: string[];
  /** The version the signature below was verified against. */
  version: string;
  detail: string;
}

export interface MlExperimentStage {
  summary: string;
  dataset: string;
  metric: string;
  /** A MEASURED figure from a real run, not a recollection. The generator requires a number in it. */
  expect: string;
}

export interface MlFailureMode {
  /** What you actually see — an exception, a number, a plot that looks wrong. */
  symptom: string;
  cause: string;
  fix: string;
}

export interface MlTrackStages {
  math: MlMathStage;
  scratch: MlScratchStage;
  library: MlLibraryStage;
  experiment: MlExperimentStage;
  failure: MlFailureMode[];
}

export interface MlTrack {
  id: string;
  title: string;
  /** A real week id from aimlCourse.ts, or null where the course genuinely has no such week. */
  weekId: string | null;
  /** Track ids that should come first. The generator proves this graph is acyclic. */
  prereqs: string[];
  minutes: number;
  /** What this track actually tests — shown before any of the work, like a question's `tests`. */
  tests: string;
  stages: MlTrackStages;
}

export const ML_TRACKS = tracksJson as MlTrack[];

export const mlTrackById: Record<string, MlTrack> = Object.fromEntries(
  ML_TRACKS.map((t) => [t.id, t]),
);

/** Stage reading order. The array is the progression — never re-sort it for display. */
export const ML_STAGE_ORDER: MlStageId[] = ['math', 'scratch', 'library', 'experiment', 'failure'];

export const ML_STAGE_LABEL: Record<MlStageId, string> = {
  math: 'The maths',
  scratch: 'From scratch',
  library: 'The library',
  experiment: 'The experiment',
  failure: 'How it breaks',
};

/** One line on why each rung exists, shown under its heading so the ladder explains itself. */
export const ML_STAGE_PURPOSE: Record<MlStageId, string> = {
  math: 'Derive it before you type it — the objective, the gradient, and what each symbol is.',
  scratch: 'Numpy only. The functions to write, in order, and the shape of every array between them.',
  library: 'Meet the implementation that already exists, and find out where it disagrees with yours.',
  experiment: 'Run both on real data. Every figure below was measured, so a disagreement is a bug.',
  failure: 'The ways this actually breaks, with the symptom you will see before you know the cause.',
};

export const totalTrackMinutes = (tracks: MlTrack[] = ML_TRACKS): number =>
  tracks.reduce((sum, t) => sum + t.minutes, 0);

export const totalFailureModes = (tracks: MlTrack[] = ML_TRACKS): number =>
  tracks.reduce((sum, t) => sum + t.stages.failure.length, 0);
